stages:
  - test

test:
  image: php7.1-extra
  script:
    - composer update --lock
    - composer install
    - vendor/bin/phpunit --configuration ./tests/testsConfig.xml tests/unitTests
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
