stages:
  - code style
  - static analysis
  - test

Code sniffer:
  stage: code style
  image: php7.4-extra
  script:
    - composer install
    - composer phpcs
  cache:
    key: $CI_COMMIT_SHORT_SHA
    paths:
      - vendor

PhpStan:
  stage: static analysis
  image: php7.4-extra
  script:
    - composer install
    - composer phpstan
  cache:
    key: $CI_COMMIT_SHORT_SHA
    paths:
      - vendor

Unit Tests PHP 7.1:
  stage: test
  image: php7.1-extra
  script:
    - composer update --lock
    - composer install
    - composer unit-tests

Unit Tests PHP 7.2:
  stage: test
  image: php7.2-extra
  script:
    - composer update --lock
    - composer install
    - composer unit-tests

Unit Tests PHP 7.3:
  stage: test
  image: php7.3-extra
  script:
    - composer update --lock
    - composer install
    - composer unit-tests

Unit Tests PHP 7.4:
  stage: test
  image: php7.4-extra
  script:
    - composer update --lock
    - composer install
    - composer unit-tests
