stages:
  - code style
  - static analysis
  - test
  - release

Code sniffer:
  stage: code style
  image: php7.4-extra
  script:
    - composer install
    - composer phpcs
  cache:
    key: $CI_COMMIT_SHORT_SHA
    paths:
      - vendor

PhpStan:
  stage: static analysis
  image: php7.4-extra
  script:
    - composer install
    - composer phpstan
  cache:
    key: $CI_COMMIT_SHORT_SHA
    paths:
      - vendor

Unit Tests PHP 7.4:
  stage: test
  image: php7.4-extra
  script:
    - composer install
    - composer unit-tests
  cache:
    key: $CI_COMMIT_SHORT_SHA
    paths:
      - vendor

Github release:
  stage: release
  image:
    name: alpine/git
    entrypoint: ['']
  when: manual
  script:
    - git clone $CI_REPOSITORY_URL $CI_COMMIT_SHORT_SHA
    - cd ${$CI_COMMIT_SHORT_SHA}
    - git remote add github https://${GITHUB_TOKEN}@github.com/arron0/testit.git
    - git push github HEAD:master --tags
  only:
    - master
    - tags
