stages:
  - test

Unit Tests PHP 7.1:
  stage: test
  image: php7.1-extra
  script:
    - composer update --lock
    - composer install
    - vendor/bin/phpunit --configuration ./tests/testsConfig.xml tests/unitTests

Unit Tests PHP 7.2:
  stage: test
  image: php7.2-extra
  script:
    - composer update --lock
    - composer install
    - vendor/bin/phpunit --configuration ./tests/testsConfig.xml tests/unitTests

Unit Tests PHP 7.3:
  stage: test
  image: php7.3-extra
  script:
    - composer update --lock
    - composer install
    - vendor/bin/phpunit --configuration ./tests/testsConfig.xml tests/unitTests

Unit Tests PHP 7.4:
  stage: test
  image: php7.4-extra
  script:
    - composer update --lock
    - composer install
    - vendor/bin/phpunit --configuration ./tests/testsConfig.xml tests/unitTests
